### PR TITLE
fixed bug with int vs. str greater-than comparison 

### PR DESCRIPTION
**Pull request by dcchivian**
... when determining largest read size.  Passing unit tests.

### CODE REVIEW

**Comment by sychan** [comment]
Your message says that it passes all unit tests, but the unit tests seems to be commented out. Why is that?

**Comment by dcchivian** [comment]
The unittest.skip()s are commented out.  I definitely ran with all of them
in.

**Comment by sychan** [comment]
@dcchivian Yes, I reread the code and realized that what was commented out was the skipping. I'm still trying to understand what the fix is, I can't seem to find a fix in the code.

**Comment by dcchivian** [comment]
backtracking code to restore bug so that subsequence PR makes clear what the fix was

**Pull request merged**
