### PR TITLE
removed bad syntax formatting on HTML report

### PR DESCRIPTION
**Pull request by dcchivian**

### CODE REVIEW

**Comment by dcchivian** [comment]
7 of 7 unit tests passing

**Comment by dcchivian** [comment]
@pranjan77 we're not permitted to merge our own PRs for Apps with more than 1 developer.  Can you do the merge please?

**Comment by pranjan77** [comment]
@dcchivian I don't have write access. So can not merge.

**Comment by dcchivian** [comment]
@pranjan77 oh, I see.  Thanks anyway.  @sychan?

**Comment by nlharris** [comment]
According to @pranjan77, this will address PUBLIC-233. Can someone (@sychan?) look at this and merge it if it looks good?

**Pull request merged**
